### ISSUE TITLE
Example or tutorial 

### ISSUE THREAD

**Issue by jihadismail8** [kenforthewin/react-redux-datatable#1]
Hi , it would be really  cool if you provide  an example code  or more detailed documents  . And perfectly  would be a small tutorial  on how to use the package  and its functions  . Thank you , please  reply  if you would do that ?

**Comment by kenforthewin** [comment]
That's a good idea. I used a Rails api server as the backend for the example gif. I'll add that repo as an example app and link to it soon.

**Comment by kenforthewin** [comment]
Added an example backend repo to the readme and here so closing the issue. https://github.com/kenforthewin/legislators-api

**Comment by keymastervn** [comment]
Hi, may I ask if you could share your frontend also, I'm trying to use it but I cannot connect the `component` with redux `store`.
Also, is `persistCombineReducers` not required, right?
